spring:
  datasource:
    url: jdbc:mysql://47.102.137.141:3306/blog?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver